name: Build Android (from PWA zip)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (cli)
        uses: android-actions/setup-android@v3

      # Cambia il nome qui se il file zip ha un altro nome/posizione
      - name: Unzip Android project from PWA Builder
        run: |
          set -e
          ZIP="Plutoo.zip"
          mkdir -p android_src
          unzip -q "$ZIP" -d android_src
          # Trova il gradlew ovunque sia finito
          GRADLEW_PATH=$(find android_src -type f -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "gradlew non trovato nello zip"
            echo "Contenuto scompattato:"
            find android_src -maxdepth 3 -type d -print
            exit 1
          fi
          APPDIR=$(dirname "$GRADLEW_PATH")
          echo "APPDIR=$APPDIR" >> $GITHUB_ENV
          echo "Trovato gradlew in: $GRADLEW_PATH"

      - name: Build debug APK
        working-directory: ${{ env.APPDIR }}
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: |
            ${{ env.APPDIR }}/app/build/outputs/apk/debug/*.apk
            ${{ env.APPDIR }}/app/build/outputs/bundle/debug/*.aab
