name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install bubblewrap
        run: npm install -g @bubblewrap/cli

      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      # FIX: auto-risposte "Yes" a Bubblewrap così installa il JDK da solo
      # e non chiede il path interattivo (che blocca il job).
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      - name: Init Android project from PWA (auto)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          # due "yes": uno per la domanda JDK e uno per confermare
          yes | yes | npx bubblewrap init \
            --manifest=https://plutoo-official.vercel.app/manifest.json \
            --directory androidapp \
            --skipPwaValidation
      # --------------------------------------------------------------------

      - name: Build APK (debug)
        working-directory: androidapp
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Plutoo-debug-apk
          path: androidapp/app/build/outputs/apk/debug/*.apk
