name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Bubblewrap CLI
        run: |
          npm i -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Resolve JDK path
        id: jdk
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "jdk_path=$JAVA_HOME" >> "$GITHUB_OUTPUT"

      - name: Init Android project from PWA (no prompts)
        env:
          MANIFEST_URL: https://mobricifilippo-del.github.io/Plutoo-app/manifest.json
          JDK_PATH: ${{ steps.jdk.outputs.jdk_path }}
        run: |
          set -e
          rm -rf android
          # Risposte automatiche ai prompt Bubblewrap:
          #  1) "Install JDK?" -> n
          #  2) "Path to your existing JDK 17:" -> $JDK_PATH
          printf 'n\n%s\n' "$JDK_PATH" | bubblewrap init \
            --manifest "$MANIFEST_URL" \
            --directory android \
            --skip-prompt

      - name: Build APK (debug)
        working-directory: android
        run: |
          bubblewrap build --skip-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
