- name: Install Android SDK
        shell: bash
        run: |
          set -e
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chown -R "$USER:$USER" "$ANDROID_SDK_ROOT"

          # Scarica i commandline-tools in una cartella temporanea
          curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/temp"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/temp"
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/temp"
          rm -f cmdtools.zip

          # Crea .../cmdline-tools/latest solo se NON esiste già
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" ]; then
            echo "cmdline-tools/latest già presente, salto il move"
          else
            mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
            # trova la cartella interna che contiene 'bin' (di solito .../temp/cmdline-tools)
            INNER=$(find "$ANDROID_SDK_ROOT/cmdline-tools/temp" -maxdepth 2 -type d -name bin | sed 's#/bin##')
            mv "$INNER"/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          fi
          rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/temp"

          # Accetta licenze e installa i pacchetti minimi per la build
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses > /dev/null
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          # Export per gli step successivi (compatibilità ANDROID_HOME)
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH
