name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Init Android project from PWA (auto answers)
        env:
          MANIFEST_URL: https://berchell.github.io/Plutoo-app/manifest.json
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        run: |
          set -e
          rm -rf android
          # Rispondiamo "n" alla domanda sul JDK e passiamo il path corretto
          printf "n\n$JAVA_HOME\n" | bubblewrap init \
            --manifest "$MANIFEST_URL" \
            --directory android \
            --skip-prompt
          test -d android && echo "Android dir OK"

      - name: Build APK (debug)
        working-directory: android
        run: bubblewrap build --skip-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
