name: Android Build

on:
  workflow_dispatch:

concurrency:
  group: android-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Install expect (for interactive answers)
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Init Android project from PWA (no prompts)
        env:
          MANIFEST_URL: https://plutoo.vercel.app/manifest.json
        run: |
          set -e
          rm -rf android
          # Risposte automatiche a tutti i prompt di bubblewrap
          expect <<'EOF'
            set timeout 1200
            spawn bubblewrap init --manifest $env(MANIFEST_URL) --directory android
            expect {
              -re {Do you want Bubblewrap to install the JDK.*\?}               { send "n\r"; exp_continue }
              -re {Path to your existing JDK 17.*:}                               { send "$env(JAVA_HOME)\r"; exp_continue }
              -re {Do you want Bubblewrap to install the Android SDK.*\?}         { send "y\r"; exp_continue }
              -re {Directory .*android does not exist.*create it now\?.*}         { send "y\r"; exp_continue }
              eof
            }
          EOF

      - name: Build APK (debug)
        working-directory: android
        run: bubblewrap build --skip-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
