name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # NEW: installiamo 'expect' per rispondere ai prompt interattivi
      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      # NEW: inizializzazione Android AUTOMATICA (risponde "n" e passa il JAVA_HOME)
      - name: Init Android project from PWA (no prompts, via expect)
        env:
          MANIFEST_URL: https://mobricifilippo-del.github.io/Plutoo-app/manifest.json
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          rm -rf android
          cat > init.exp <<'EOF'
          #!/usr/bin/expect -f
          set timeout -1
          set jdk $env(JAVA_HOME)
          set manifest $env(MANIFEST_URL)
          spawn bubblewrap init --manifest $manifest --directory android --skipPrompt
          expect {
            -re {Do you want Bubblewrap to install the JDK.*\?} { send "n\r"; exp_continue }
            -re {Path to your existing JDK 17:} { send "$jdk\r"; exp_continue }
            eof
          }
          EOF
          chmod +x init.exp
          ./init.exp

      - name: Build APK (debug)
        working-directory: android
        run: bubblewrap build --skipPrompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
