name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      # 🔧 Ricavo il path del JDK reale e lo salvo in $JDK_PATH
      - name: Resolve JDK path
        run: |
          set -e
          JDK_PATH="$(dirname "$(dirname "$(readlink -f "$(which javac)")")")"
          echo "JDK_PATH=$JDK_PATH" >> $GITHUB_ENV
          echo "Using JDK_PATH=$JDK_PATH"

      - name: Init Android project from PWA (no prompts)
        env:
          MANIFEST_URL: "https://mobricifilippo-del.github.io/Plutoo-app/manifest.json"
        run: |
          set -e
          npx bubblewrap init \
            --manifest "$MANIFEST_URL" \
            --directory android \
            --skip-prompt \
            --jdkPath "$JDK_PATH"

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
