name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Init Android project from PWA (force no prompts)
        env:
          MANIFEST_URL: https://mobricifilippo-del.github.io/Plutoo-app/manifest.json
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          rm -rf android
          bubblewrap init \
            --manifest "$MANIFEST_URL" \
            --directory android \
            --jdkPath "$JAVA_HOME" \
            --skipPwaValidation \
            --skipPrompt \
            --packageId com.plutoo.app \
            --name "Plutoo" \
            --appVersionName 1.0.0 \
            --appVersionCode 1 \
            --host plutoo-app

      - name: Build APK (debug)
        working-directory: android
        run: bubblewrap build --skipPrompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
