name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting Android build..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Prepare android dir
        run: mkdir -p android

      - name: Init Android project from PWA (no prompts)
        run: |
          bubblewrap init --manifest=https://plutoo.vercel.app/manifest.json --directory android --skip-prompt

      - name: Build APK (debug)
        run: |
          cd android
          bubblewrap build --skip-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
