name: Android Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # evita run infiniti

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Setup JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Debug JDK
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          $JAVA_HOME/bin/java -version
          which java || true
          java -version || true

      # Use "expect" con pattern più ampi e timeout, per rispondere ai prompt
      - name: Init Android project from PWA (no prompts, with expect)
        env:
          MANIFEST_URL: https://mobricifilippo-del.github.io/Plutoo-app/manifest.json
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y expect
          rm -rf android

          cat > do_init.exp <<'EOF'
          #!/usr/bin/expect -f
          set timeout 120
          log_user 1
          set jdk $env(JAVA_HOME)
          set manifest $env(MANIFEST_URL)

          # Avvia init
          spawn bubblewrap init --manifest $manifest --directory android --skip-prompt

          # 1) domanda JDK (testo può variare, usiamo regex ampia)
          expect {
            -re {install.*JDK.*\?} { send "n\r" }
            timeout {
              send_user "\n[ERR] Prompt JDK non visto entro 120s\n"
              exit 2
            }
          }

          # 2) richiesta percorso JDK (regex ampia)
          expect {
            -re {Path.*existing.*JDK.*:} { send "$jdk\r" }
            timeout {
              send_user "\n[ERR] Prompt percorso JDK non visto entro 120s\n"
              exit 3
            }
          }

          # Fine
          expect eof
          EOF

          chmod +x do_init.exp
          ./do_init.exp

      - name: Build APK (debug)
        working-directory: android
        run: bubblewrap build --skip-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: plutoo-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
