name: Make PWA Icons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Generate icons
        run: |
          mkdir -p icons
          convert plutoo-icon-512.png -resize 192x192 icons/icon-192.png
          convert plutoo-icon-512.png -resize 512x512 icons/icon-512.png
          convert plutoo-icon-512.png -resize 512x512 icons/icon-512-maskable.png

      - name: Upload icons
        uses: actions/upload-artifact@v4
        with:
          name: pwa-icons
          path: icons/
