name: Make PWA Icons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Generate icons
        run: |
          mkdir -p icons
          convert plutoo-icon-512.png -resize 192x192 icons/icon-192.png
          convert plutoo-icon-512.png -resize 512x512 icons/icon-512.png

      - name: Move icons to repo root
        run: |
          mv -f icons/icon-192.png icon-192.png
          mv -f icons/icon-512.png icon-512.png

      - name: Commit icons
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add PWA icons"
          file_pattern: "icon-192.png icon-512.png"
